---
title: "Two-group hypothesis testing"
output: html_document
---

In my previous posts, I asked you to imagine that we work for a retail website that sells children's toys. In the past, they asked us to estimate the mean number of page views per day (see here and here for my posts discussing this problem). Now, they've launched two online advertising campaigns, and they want us to see if they generate different amounts of income for the site.

After taking [representative samples](post) of the revenue generated from each campaign, we then carry out a hypothesis test. The usual workflow of hypothesis testing is as follows:
1. Define your question;
2. Define your hypotheses;  
3. Pick the most likely appropriate test distribution (t, z, binomial, etc.);  
4. Compute your test statistic;  
5. Work out whether we reject the null hypothesis based whether your test statistic exceeds a critical statistic under this distribution. (This is where we pick the rejection region for the null hypothesis.)

Let's work through each of these steps in detail.

## Defining your question
I've spoken a bit about this [previously](representative samples post), but an important first step to any analysis is working out _what you are asking_ and _how you will measure it_. A reasonable way to measure this question could be taking all site visits that originate from each of the campaigns and see how many purchases result (in dollars). The way to test whether they generate different amounts of income could be to calculate the mean of each group and see if it differs.

## Defining your hypotheses
In hypothesis testing, you are trying to compare two possible outcomes. The first is the **null hypothesis** (H$\sf{_{0}}$), which represents the "status quo" and is assumed to be correct until statistical evidence is presented that allows us to reject it. In this case, the null hypothesis is that there is no difference between the mean amount of income generated by each campaign. Stating this more formally, we get:

H$\sf{_{0}}$: $\mu\sf{_{1}}$ = $\mu\sf{_{2}}$, or $\mu\sf{_{1}}$ - $\mu\sf{_{2}}$ = 0
where $\mu\sf{_{1}}$ is the mean of the first population, and $\mu\sf{_{2}}$ is the mean of the second population.

The **alternative** hypothesis (H$\sf{_{a}}$) is that there is a difference between the mean level of incomes generated by each campaign. More formally, the alternative hypothesis is:
H$\sf{_{a}}$: $\mu\sf{_{1}}$ &#8800; $\mu\sf{_{2}}$, or $\mu\sf{_{1}}$ - $\mu\sf{_{2}}$ &#8800; 0

In other words, we are trying to test whether the difference in the mean levels of income generated by each campaign is sufficiently different from 0 (no difference).

## Picking the most appropriate distribution
The most appropriate distribution depends on what we _assume the population distribution is_. In the case of average income from each campaign, I am going to assume they are reasonably normally distributed. However, we're under a bit of pressure to get the results out quickly so we've only been able to get a small sample size for each campaign. As such, the Student's t distribution would be a safer bet.

## Computing your test statistic
The **test statistic** is simply the 


Earlier I said that the null hypothesis and the alternative hypothesis can be reframed as H$\sf{_{0}}$: $\mu\sf{_{1}}$ - $\mu\sf{_{2}}$ = 0; H$\sf{_{a}}$: $\mu\sf{_{1}}$ - $\mu\sf{_{2}}$ &#8800; 0. The consequence of this is that our 




Confidence interval for t-test:
$\bar X\sf{_{1}}$ - $\bar X\sf{_{2}}$ &plusmn; _t_(_n_$\sf{_{1}}$ + _n_$\sf{_{2}}$ - 2), 1 - $\alpha$ / 2 * 

```{r}
data("ToothGrowth")

require(psych); require(tidyr); require(ggplot2)
describe(ToothGrowth$len[ToothGrowth$supp == "OJ"])
describe(ToothGrowth$len[ToothGrowth$supp == "VC"])

sp <- sqrt((30 * 6.61^2 + 30 * 8.27^2)/(30 + 30 - 2))
0 + c(-1, 1) * qt(.975, 28) * sp * (1/30 + 1/30)^.5
20.66 - 16.96

t.test(ToothGrowth$len[ToothGrowth$supp == "OJ"], ToothGrowth$len[ToothGrowth$supp == "VC"], 
       paired = FALSE, var.equal = TRUE)

# Estimate 1 SEM around 0 for the test distribution:

sem <- 0 + 1 * qt(.84, 28) * sp * (1/30 + 1/30)^.5

lci <- -1 * qt(.975, 28) * sp * (1/30 + 1/30)^.5
uci <- 1 * qt(.975, 28) * sp * (1/30 + 1/30)^.5

line1 <- data.frame(lines="95% CI of no difference", vals = c(lci, uci))
line2 <- data.frame(lines="Test statistic", 
                    vals = mean(ToothGrowth$len[ToothGrowth$supp == "OJ"]) - 
                        mean(ToothGrowth$len[ToothGrowth$supp == "VC"]))
lines <- rbind(line1, line2)

ggplot(data.frame(x = c(-5, 5)), aes(x)) + 
    stat_function(fun = dt, args = list(df = 28)) +
    xlab("Difference in mean income") + 
    ylab("Density") + 
    theme_bw() +
    geom_vline(data=lines, aes(xintercept=vals, linetype = lines, 
                        colour = lines), size = 1, show_guide = TRUE) + 
    scale_color_manual(values=c("95% CI" = "black", 
                                "Test statistic" = "black"))
```

SEM = `r sem`

The distribution the critical T and test statistic are calculated under is the distribution of difference between means (as we are trying to see whether difference as extreme is likely under this distribution). This is given by (mean = difference between groups means, se = pooled sd / sqrt(n))

As you can see, a major part of this process is having data that fit the assumptions of your chosen distribution. What if this is not the case? 